package com.lobmatrix.wal;

import java.nio.file.Path;

/**
 * Audit report generated by WALCrashRecoveryEngine after scanning and recovering a .raw WAL file.
 */
public record WALRecoveryReport(
        Path filePath,
        long originalSizeBytes,
        long recoveredSizeBytes,
        long validFramesCount,
        boolean wasCorrupted,
        String diagnosis
) {
    public long bytesTruncated() {
        return originalSizeBytes - recoveredSizeBytes;
    }
}
